/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package runewordfinder

import java.io.InputStream
import java.io.OutputStream

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun handler(input: InputStream, output: OutputStream): String {
    println(App().greeting)
    return App().greeting
}
